platform :ios, '10.0'
inhibit_all_warnings!

target 'Rtoken' do
  use_frameworks!
  pod 'BigInt'
  pod 'R.swift'
#R.swift就是为解决这个问题而生，具有强类型关联、编译错误检查、自动代码填充的功能，即安全又方便。基本原理就是在Xcode每次build期间自动读取解析工程目录内引用的资源文件以及创建的资源文件（例如TableViewCell.nib），将这些资源以代码的形式封装在一个动态生成的R.generated.swift的文件中。例如我在Assets.xcassets中添加了一个settings_icon图标，编译后R.generated.swift中将自动得到下面的代码段：
  
  pod 'APIKit'
   #也使用了JSONRPCKit + APIKit的框架去进行数据请求
  pod 'PromiseKit'
  
  pod 'Eureka'   #Eureka可以帮你简单优雅的实现动态table-view表单。它由rows,sections和forms组成。如果你的app包含大量表单，Eureka可以真正帮你节省时间。
  pod 'MBProgressHUD'
  
  
  pod 'StatefulViewController'   #一种协议，用于使UIViewControllers或UIViews能够根据内容，加载，错误或空状态显示占位符视图。
  
  pod 'QRCodeReaderViewController'
  pod 'KeychainSwift'
  #keychain来保存比较重要且轻量的数据, 如私钥、应用锁设置和密码、最近使用的钱包、Browser的cookies
  pod 'SwiftLint'
  #    #一个强大的Swift风格和约定的工具
  #    pod 'SeedStackViewController'
  #    #它简化了使用构建表单和其他静态内容的过程UIStackView
  pod 'RealmSwift'#Realm数据库, 这是个轻量级、高性能、高效率、可跨平台的移动数据库。核心数据如钱包账户、交易、Token等都存储于此
  
  pod 'Moya'#Moya进行数据请求
  pod 'CryptoSwift'#在Swift中实现的加密相关函数
  pod 'Kingfisher'#Kingfisher 是一个下载、缓存网络图片的轻量级纯swift库
  pod 'TrustCore'  , :git=>'https://github.com/TrustWallet/trust-core', :branch=>'master'
  #核心以太坊数据结构和算法
  pod 'TrustKeystore'  , :git=>'https://github.com/TrustWallet/trust-keystore', :branch=>'master'
  # 应用的核心业务的处理类, 有钱包管理(创建、删除、导入、导出)、助记词转化、签名工作、私钥管理等功能。用于管理钱包的通用以太坊密钥库。这是适用于iOS的Trust Ethereum Wallet的一部分，但可以单独使用。它支持：
  #
  #    #从私钥创建新钱包
  #    #加载JSON钱包文件
  #    # 加载BIP39助记短语备份
  #    #签署哈希
  pod 'TrezorCrypto'
  #围绕trezor-crypto C库
  pod 'URLNavigator'
  #URLNavigator提供了一种通过URL导航视图控制器的优雅方式。可以使用URLNavigator.register(_:_:)函数映射URL模式。
  #    #URLNavigator可用于映射具有两种类型的URL模式：URLNavigable和URLOpenHandler。URLNavigable是一个定义自定义初始化程序的类型，URLOpenHandler是一个可以执行的闭包。初始化器和闭包都接收URL和占位符值。
  #    pod 'Branch'
  #    #在启动应用时进行初始化, 并将在应用程序生命周期中多次调用，当应用由后台向前台切换时也将调用。用于处理从外部跳转入后, 根据传入的参数要跳转进入指定的页面。
  pod 'SAMKeychain'
  #    #SAMKeychain是一个简单的包装器，用于在Mac OS X和iOS上使用系统Keychain访问帐户，获取密码，设置密码和删除密码。
  pod 'TrustWeb3Provider', :git=>'https://github.com/TrustWallet/trust-web3-provider', :commit=>'f4e0ebb1b8fa4812637babe85ef975d116543dfd'
  
  
#  pod 'JSONRPCKit'

  #    pod 'TrustSDK'
  #   pod 'TrustWalletSDK'  , :git=>'https://github.com/TrustWallet/TrustSDK-iOS', :branch=>'master'
end

