//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 7 images.
  struct image {
    /// Image `fanhuiir`.
    static let fanhuiir = Rswift.ImageResource(bundle: R.hostingBundle, name: "fanhuiir")
    /// Image `fenlei_nor`.
    static let fenlei_nor = Rswift.ImageResource(bundle: R.hostingBundle, name: "fenlei_nor")
    /// Image `fenlei_pre`.
    static let fenlei_pre = Rswift.ImageResource(bundle: R.hostingBundle, name: "fenlei_pre")
    /// Image `shouye_nor`.
    static let shouye_nor = Rswift.ImageResource(bundle: R.hostingBundle, name: "shouye_nor")
    /// Image `shouye_per`.
    static let shouye_per = Rswift.ImageResource(bundle: R.hostingBundle, name: "shouye_per")
    /// Image `wode_nor`.
    static let wode_nor = Rswift.ImageResource(bundle: R.hostingBundle, name: "wode_nor")
    /// Image `wode_pre`.
    static let wode_pre = Rswift.ImageResource(bundle: R.hostingBundle, name: "wode_pre")
    
    /// `UIImage(named: "fanhuiir", bundle: ..., traitCollection: ...)`
    static func fanhuiir(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fanhuiir, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "fenlei_nor", bundle: ..., traitCollection: ...)`
    static func fenlei_nor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fenlei_nor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "fenlei_pre", bundle: ..., traitCollection: ...)`
    static func fenlei_pre(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fenlei_pre, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shouye_nor", bundle: ..., traitCollection: ...)`
    static func shouye_nor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shouye_nor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "shouye_per", bundle: ..., traitCollection: ...)`
    static func shouye_per(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shouye_per, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "wode_nor", bundle: ..., traitCollection: ...)`
    static func wode_nor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wode_nor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "wode_pre", bundle: ..., traitCollection: ...)`
    static func wode_pre(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wode_pre, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
